backend:
  name: github
  repo: dancesWithCycles/ws-hugo
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "draft", label: "Draft", widget: "boolean", default: false }
      - { name: "body", label: "Body", widget: "markdown" }
